server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: ${SERVER_NAME:k8s-gateway}
  cloud:
    gateway:
      routes:
        - id: web
          uri: lb://k8s-web
          predicates:
            - Path=/web/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOST_NAME:localhost}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
tools:
  doc:
    group:
      enable: true
      service-list:
        - desc: 服务A
          target: web